version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: home-express-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: home_express
      MYSQL_USER: homeexpress
      MYSQL_PASSWORD: homeexpress123
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
    networks:
      - home-express-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: home-express-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword123
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - home-express-network
    restart: unless-stopped

volumes:
  mysql_data:


networks:
  home-express-network:
    driver: bridge
