spring:
  application:
    name: home-express-api

  datasource:
    url: jdbc:mysql://localhost:3306/home_express
    username: homeexpress
    password: homeexpress123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  security:
    user:
      name: admin
      password: admin123

server:
  port: 8081

logging:
  level:
    com.homeexpress.api: DEBUG
    org.springframework.security: DEBUG